name: oxytocin_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - jupyter
  - ipympl
  - matplotlib
  - faiss
  - tqdm
  - pip
  - pip:
    - --extra-index-url https://download.pytorch.org/whl/cu118
    - torch
    - kilosort[gui]
    - pynwb
    - git+https://github.com/open-ephys/open-ephys-python-tools.git@archive

