name: brainpatch_analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.9
  - numpy
  - pandas
  - matplotlib
  - ipympl
  - jupyter
  - pip:
      - kilosort==4.0.16
      - open-ephys-python-tools==0.1.12
      - tqdm
